
# Time series features  

```{r}
library(tsibble)
library(tsibbledata)
library(fable)
library(feasts)
```


## Simple statistics  


## ACF features  


## STL features  


$$
y_t = T_t + S_t + R_t
$$



$$
F_T = \max(0\,, 1- \frac{Var(R_t)}{Var(T_t + R_t)})
$$

$$
F_S = \max(0\,, 1- \frac{Var(R_t)}{Var(S_t + R_t)})
$$



```{r}
tourism %>%
  features(Trips, feat_stl)
```

```{r}
tourism %>%
  features(Trips, feat_stl) %>%
  ggplot() + 
  geom_point(aes(trend_strength, seasonal_strength_year, color = Purpose))
```

All of the features included in the `feasts` package can be computed in one line like this, which gives total 44 features (result not show).  

```{r, eval = FALSE}
tourism %>% 
  features(Trips, feature_set(pkgs = "feasts"))
```


## Exporing Australian tourism data  

Specify multiple function

```{r, cache = TRUE}
tourism_tsl <- tourism %>%
  features(Trips, features = list(feat_stl, feat_acf))
```


```{r, fig.height = 8, cache = TRUE}
tourism_tsl %>% 
  select(contains("season"), Purpose) %>% 
  mutate(
    seasonal_peak_year = glue::glue("Q{seasonal_peak_year + 1}"),
    seasonal_trough_year = glue::glue("Q{seasonal_trough_year + 1}")) %>%
  GGally::ggpairs(aes(color = Purpose))
```




