

# Judgmental forecasts  

There are three general settings in which judgmental forecasting is used:  

- there are no available data so that statistical methods are not applicable and judgmental forecasting is the only feasible approach  
- data are available, statistical forecasts are generated, and these are then adjusted using judgement
- data are available and statistical and judgmental forecasts are generated independently and then combined  


> It is important to recognise that judgmental forecasting is subjective and comes with limitations. However, implementing systematic and well-structured approaches can confine these limitations and markedly improve forecast accuracy.  



Whenever data are available, applying statistical methods (such as those discussed in other chapters of this book), is preferable and should always be used as a starting point.  

## Beware of limitations  

Judgmental forecasts are subjective, and therefore do not come free of bias or limitations.

Judgmental forecasts can be inconsistent. Unlike statistical forecasts, which can be generated by the same mathematical formulas every time, judgmental forecasts depend heavily on human cognition, and are vulnerable to its limitations.  

Judgement can be clouded by personal or political agendas, where targets and forecasts (as defined in Chapter \@ref(getting-started)) are not segregated. 

Another undesirable property which is commonly seen in judgmental forecasting is the effect of anchoring. In this case, the subsequent forecasts tend to converge or be close to an initial familiar reference point  

## Key principles 







